/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import internalPages.manageUser;
/**
 *
 * @author Admin
 */
public class dashBoardPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form dashboard
     */
    public dashBoardPage() {
        initComponents();
        
      this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
      BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
      bi.setNorthPane(null);
    }
     Color navcolor = new Color (102,102,102);
     Color headcolor = new Color (51,51,51);
     Color bodycolor = new Color (153,153,153);
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        manageUser = new javax.swing.JPanel();
        username1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        members = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        username3 = new javax.swing.JLabel();
        settings = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        username4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GYM MANAGEMENT SYSTEM");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 490, -1));

        manageUser.setBackground(new java.awt.Color(204, 204, 204));
        manageUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageUserMouseExited(evt);
            }
        });
        manageUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username1.setBackground(new java.awt.Color(0, 0, 0));
        username1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username1.setText("MANAGE USER");
        manageUser.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/manager-user.png"))); // NOI18N
        manageUser.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 100));

        jPanel2.add(manageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 150, 130));

        members.setBackground(new java.awt.Color(204, 204, 204));
        members.setPreferredSize(new java.awt.Dimension(160, 160));
        members.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                membersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                membersMouseExited(evt);
            }
        });
        members.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/members.png"))); // NOI18N
        members.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 60));

        username3.setBackground(new java.awt.Color(0, 0, 0));
        username3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username3.setText("MEMBERS");
        members.add(username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, -1));

        jPanel2.add(members, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, 130));

        settings.setBackground(new java.awt.Color(204, 204, 204));
        settings.setPreferredSize(new java.awt.Dimension(160, 160));
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsMouseExited(evt);
            }
        });
        settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/settings.png"))); // NOI18N
        settings.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 100));

        username4.setBackground(new java.awt.Color(0, 0, 0));
        username4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username4.setText("SETTINGS");
        settings.add(username4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, -1));

        jPanel2.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 150, 130));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 330));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 930, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserMouseEntered
        manageUser.setBackground(navcolor);
    }//GEN-LAST:event_manageUserMouseEntered

    private void manageUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserMouseExited
         manageUser.setBackground(headcolor);
    }//GEN-LAST:event_manageUserMouseExited

    private void membersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseEntered
        members.setBackground(navcolor);
    }//GEN-LAST:event_membersMouseEntered

    private void membersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseExited
       members.setBackground(headcolor);
    }//GEN-LAST:event_membersMouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void settingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseEntered
      settings.setBackground(navcolor);
    }//GEN-LAST:event_settingsMouseEntered

    private void settingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseExited
     settings.setBackground(headcolor);
    }//GEN-LAST:event_settingsMouseExited

    private void membersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseClicked
   // 1. Get the main window without using the word "dashboard"
    javax.swing.JFrame topFrame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
    
    try {
        // 2. Find your blue area (maindesktop) inside that window
        java.lang.reflect.Field desktopField = topFrame.getClass().getDeclaredField("maindesktop");
        desktopField.setAccessible(true);
        javax.swing.JDesktopPane desktop = (javax.swing.JDesktopPane) desktopField.get(topFrame);
        
        // 3. Clear and show the Member page
        desktop.removeAll();
        member m = new member();
        desktop.add(m).setVisible(true);
        
        // 4. Update the screen
        desktop.revalidate();
        desktop.repaint();
        
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
    }//GEN-LAST:event_membersMouseClicked

    private void manageUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserMouseClicked
    try {
        // 1. Create the internal frame from the internalPages package
        internalPages.manageUser userPage = new internalPages.manageUser();
        
        // 2. Get the main window (your dashBoard)
        Object topFrame = javax.swing.SwingUtilities.getWindowAncestor(this);
        
        // 3. Find the 'maindesktop' variable inside the dashBoard class
        java.lang.reflect.Field desktopField = topFrame.getClass().getDeclaredField("maindesktop");
        desktopField.setAccessible(true);
        javax.swing.JDesktopPane desktop = (javax.swing.JDesktopPane) desktopField.get(topFrame);
        
        // 4. Clear the current view and show the User page
        desktop.removeAll();
        desktop.add(userPage).setVisible(true);
        
        // 5. Refresh the UI
        desktop.revalidate();
        desktop.repaint();
        
    } catch (Exception e) {
        // This will print if the variable name 'maindesktop' is spelled wrong
        System.out.println("Error: " + e.getMessage());
    }
    }//GEN-LAST:event_manageUserMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel manageUser;
    private javax.swing.JPanel members;
    private javax.swing.JPanel settings;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username3;
    private javax.swing.JLabel username4;
    // End of variables declaration//GEN-END:variables
}
