/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import java.awt.Color;

/**
 *
 * @author Admin
 */
public class manageUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form manageUser
     */
   public manageUser() {
        initComponents();
        // Just the name here to "call" it
        displayData(); 
    }

    // Move the actual function definition DOWN here, outside the constructor
    public void displayData() {
    config.configclass cc = new config.configclass();
    // Removed the last name column to match your database structure
    cc.displayData("SELECT u_id as 'ID', u_fname as 'First Name', "
                 + "u_email as 'Email', u_phone as 'Phone', u_username as 'Username', "
                 + "u_status as 'Status' FROM users", user_table);
}
    
    // ... rest of your code (like navcolor variables)
        Color navcolor = new Color (102,102,102);
        Color headcolor = new Color (51,51,51);
        Color bodycolor = new Color (153,153,153);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        user_table = new javax.swing.JTable();
        search3 = new javax.swing.JTextField();
        searchUser = new javax.swing.JPanel();
        search = new javax.swing.JLabel();
        refresh = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(51, 51, 51));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("USERS");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel14.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 150, 20));

        jPanel15.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 40));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        jPanel16.setBackground(new java.awt.Color(153, 153, 153));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_table.setAutoCreateRowSorter(true);
        user_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        user_table.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        user_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "member ID", "First Name", "Email", "Phone", "Username", "Password", "Status"
            }
        ));
        user_table.setSelectionBackground(new java.awt.Color(102, 102, 102));
        user_table.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane4.setViewportView(user_table);

        jPanel16.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 700, 280));

        search3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        search3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search3.setOpaque(false);
        search3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search3MouseClicked(evt);
            }
        });
        search3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search3ActionPerformed(evt);
            }
        });
        jPanel16.add(search3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 200, 30));

        searchUser.setBackground(new java.awt.Color(102, 102, 102));
        searchUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchUserMouseExited(evt);
            }
        });
        searchUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setBackground(new java.awt.Color(51, 51, 51));
        search.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search.setText("SEARCH");
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchUser.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel16.add(searchUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 80, 30));

        refresh.setBackground(new java.awt.Color(153, 153, 153));
        refresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshMouseExited(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N

        javax.swing.GroupLayout refreshLayout = new javax.swing.GroupLayout(refresh);
        refresh.setLayout(refreshLayout);
        refreshLayout.setHorizontalGroup(
            refreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        refreshLayout.setVerticalGroup(
            refreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, refreshLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel16.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 30, 30));

        jPanel13.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 750, 380));

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_search3MouseClicked

    private void search3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search3ActionPerformed

    }//GEN-LAST:event_search3ActionPerformed

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
       // 1. Clear the white text field (search3), NOT the button label (search)
    search3.setText(""); 
    
    // 2. Reset the button text just in case it was deleted
    search.setText("SEARCH"); 
    
    // 3. Reload the table data
    displayData();
    }//GEN-LAST:event_refreshMouseClicked

    private void refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseEntered
        refresh.setBackground(bodycolor);
    }//GEN-LAST:event_refreshMouseEntered

    private void refreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseExited
        refresh.setBackground(navcolor);
    }//GEN-LAST:event_refreshMouseExited

    private void searchUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchUserMouseExited
        searchUser.setBackground(navcolor);
    }//GEN-LAST:event_searchUserMouseExited

    private void searchUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchUserMouseEntered
        searchUser.setBackground(bodycolor);
    }//GEN-LAST:event_searchUserMouseEntered

    private void searchUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchUserMouseClicked
     config.configclass conf = new config.configclass();
    
    // 1. Get the text from 'search3' (the white box in your Navigator)
    String txt = search3.getText(); 
    
    // 2. Query matches your 'users' table and avoids the missing 'u_Iname' column
    String query = "SELECT u_id AS 'ID', u_fname AS 'First Name', "
                 + "u_email AS 'Email', u_status AS 'Status' FROM users "
                 + "WHERE u_fname LIKE '%" + txt + "%' OR u_id LIKE '%" + txt + "%' OR u_email LIKE '%" + txt + "%'";

    // 3. Display results in your 'user_table'
    conf.displayData(query, user_table);
    }//GEN-LAST:event_searchUserMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel refresh;
    private javax.swing.JLabel search;
    private javax.swing.JTextField search3;
    private javax.swing.JPanel searchUser;
    public javax.swing.JTable user_table;
    // End of variables declaration//GEN-END:variables
}
