/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import java.awt.Color;

/**
 *
 * @author USER42
 */
public class userprofile extends javax.swing.JInternalFrame {

    /**
     * Creates new form accountsettings
     */
    public userprofile() {
        initComponents();
    }
    Color navcolor = new Color (102,102,102);
     Color headcolor = new Color (51,51,51);
     Color bodycolor = new Color (153,153,153);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fullname = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        p_email = new javax.swing.JLabel();
        p_name = new javax.swing.JLabel();
        p_id = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        manageUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        manageUser1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        username2 = new javax.swing.JLabel();
        members = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        username3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullname.setBackground(new java.awt.Color(204, 204, 204));
        fullname.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        fullname.setForeground(new java.awt.Color(204, 204, 204));
        fullname.setText("Full name: ");
        jPanel2.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 30));

        email.setBackground(new java.awt.Color(204, 204, 204));
        email.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        email.setForeground(new java.awt.Color(204, 204, 204));
        email.setText("Email: ");
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 120, 30));

        ID.setBackground(new java.awt.Color(204, 204, 204));
        ID.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        ID.setForeground(new java.awt.Color(204, 204, 204));
        ID.setText("User ID: ");
        jPanel2.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 30));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 100));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 160, 140));

        p_email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        p_email.setForeground(new java.awt.Color(204, 204, 204));
        p_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(p_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 180, 30));

        p_name.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        p_name.setForeground(new java.awt.Color(204, 204, 204));
        p_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 180, 30));

        p_id.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        p_id.setForeground(new java.awt.Color(204, 204, 204));
        p_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 180, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 190));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageUser.setBackground(new java.awt.Color(204, 204, 204));
        manageUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageUserMouseExited(evt);
            }
        });
        manageUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/attendance.png"))); // NOI18N
        manageUser.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 110));

        username1.setBackground(new java.awt.Color(0, 0, 0));
        username1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username1.setText("ATTENDANCE");
        manageUser.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, -1));

        jPanel3.add(manageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 170, 150));

        manageUser1.setBackground(new java.awt.Color(204, 204, 204));
        manageUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageUser1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageUser1MouseExited(evt);
            }
        });
        manageUser1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reports.png"))); // NOI18N
        manageUser1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 110));

        username2.setBackground(new java.awt.Color(0, 0, 0));
        username2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username2.setText("REPORTS");
        manageUser1.add(username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 20));

        jPanel3.add(manageUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 170, 150));

        members.setBackground(new java.awt.Color(204, 204, 204));
        members.setPreferredSize(new java.awt.Dimension(160, 160));
        members.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                membersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                membersMouseExited(evt);
            }
        });
        members.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        members.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 110));

        username3.setBackground(new java.awt.Color(0, 0, 0));
        username3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username3.setText("LOG OUT");
        members.add(username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, -1));

        jPanel3.add(members, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, 150));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 690, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserMouseEntered
        manageUser.setBackground(navcolor);
    }//GEN-LAST:event_manageUserMouseEntered

    private void manageUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserMouseExited
        manageUser.setBackground(headcolor);
    }//GEN-LAST:event_manageUserMouseExited

    private void manageUser1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUser1MouseEntered
        manageUser.setBackground(navcolor);
    }//GEN-LAST:event_manageUser1MouseEntered

    private void manageUser1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUser1MouseExited
        manageUser.setBackground(headcolor);
    }//GEN-LAST:event_manageUser1MouseExited

    private void membersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseClicked
        // 1. Get the main window without using the word "dashboard"
        javax.swing.JFrame topFrame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        try {
            // 2. Find your blue area (maindesktop) inside that window
            java.lang.reflect.Field desktopField = topFrame.getClass().getDeclaredField("maindesktop");
            desktopField.setAccessible(true);
            javax.swing.JDesktopPane desktop = (javax.swing.JDesktopPane) desktopField.get(topFrame);

            // 3. Clear and show the Member page
            desktop.removeAll();
            member m = new member();
            desktop.add(m).setVisible(true);

            // 4. Update the screen
            desktop.revalidate();
            desktop.repaint();

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_membersMouseClicked

    private void membersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseEntered
        members.setBackground(navcolor);
    }//GEN-LAST:event_membersMouseEntered

    private void membersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseExited
        members.setBackground(headcolor);
    }//GEN-LAST:event_membersMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ID;
    public javax.swing.JLabel email;
    public javax.swing.JLabel fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel manageUser;
    private javax.swing.JPanel manageUser1;
    private javax.swing.JPanel members;
    public javax.swing.JLabel p_email;
    public javax.swing.JLabel p_id;
    public javax.swing.JLabel p_name;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username3;
    // End of variables declaration//GEN-END:variables
}
