package main_app;


import config.PasswordHasher;
import main_app.dashboard;
import config.Session;
import config.Singleton;
import config.configclass;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class logIn extends javax.swing.JFrame {

    /**
     * Creates new form logIn
     */
    public logIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        uname1 = new javax.swing.JTextField();
        username1 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        showpass = new javax.swing.JCheckBox();
        sigin = new javax.swing.JButton();
        passField = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uname1.setBackground(new java.awt.Color(204, 204, 204));
        uname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uname1ActionPerformed(evt);
            }
        });
        jPanel2.add(uname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, 30));

        username1.setBackground(new java.awt.Color(204, 204, 204));
        username1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username1.setForeground(new java.awt.Color(255, 255, 255));
        username1.setText("Enter Username:");
        jPanel2.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        username.setBackground(new java.awt.Color(204, 204, 204));
        username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Enter Password:");
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        showpass.setBackground(new java.awt.Color(102, 102, 102));
        showpass.setForeground(new java.awt.Color(204, 204, 204));
        showpass.setText("Show Password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        jPanel2.add(showpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        sigin.setBackground(new java.awt.Color(255, 255, 255));
        sigin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sigin.setForeground(new java.awt.Color(51, 51, 51));
        sigin.setText("Sign in");
        sigin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                siginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                siginMouseExited(evt);
            }
        });
        sigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siginActionPerformed(evt);
            }
        });
        jPanel2.add(sigin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        passField.setBackground(new java.awt.Color(204, 204, 204));
        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        jPanel2.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 540, 410));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("LOG IN FORM");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 220, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siginActionPerformed
    String user = username.getText().toString();
            String pass = passField.getText().toString();
            if(username.getText().isEmpty() || passField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "All Fields are Required!");
            }else{
            try {
                   String rehashedPassword;
                   String hashedpass;
                configclass  dbc= new configclass();
                ResultSet rs = dbc.getData("SELECT * FROM tbl_user WHERE user_email = '"+user+"'");
                    if(rs.next()){
                        hashedpass = rs.getString("password");
                         rehashedPassword = PasswordHasher.hashPassword(pass);
                        if(user.equals(rs.getString("user_email")) && hashedpass.equals(rehashedPassword)){
                            JOptionPane.showMessageDialog(null, "Login Success!");
                            dashboard dash = new dashboard();
                            this.dispose();
                            dash.setVisible(true);
                            
                            Singleton singletonInstance = Singleton.getInstance();
                            int id = rs.getInt("user_id");
                            String fname = rs.getString("user_fname");
                            String lname = rs.getString("user_lname");
                            String email = rs.getString("user_email");
                            String users = rs.getString("username");
                            String status = rs.getString("user_status");
                            
                            System.out.println("newData: "+id);
                            singletonInstance.setId(id);
                            singletonInstance.setFname(fname);
                            singletonInstance.setLname(lname);
                            singletonInstance.setEmail(email);
                            singletonInstance.setUsername(users);
                            singletonInstance.setStatus(status);
                            
                        }else{
                            JOptionPane.showMessageDialog(null, "Invalid Account!");
                            passField.setText("");
                        }
                    }else{
                        System.out.println("No data Found");
                    }
            } catch (NoSuchAlgorithmException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Server Connection Failed!");
            }
            }
    }//GEN-LAST:event_siginActionPerformed

    private void siginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siginMouseExited

    }//GEN-LAST:event_siginMouseExited

    private void siginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siginMouseEntered

    }//GEN-LAST:event_siginMouseEntered

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        if (showpass.isSelected()) {
        passField.setEchoChar((char)0); // Now this works!
    } else {
        passField.setEchoChar('*');    
    }
    }//GEN-LAST:event_showpassActionPerformed

    private void uname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uname1ActionPerformed
      
    }//GEN-LAST:event_uname1ActionPerformed

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField passField;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JButton sigin;
    private javax.swing.JTextField uname1;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    // End of variables declaration//GEN-END:variables
}
