/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main_app;

import config.configclass;
import internalPages.manageUser;
import javax.swing.JOptionPane;

/**
 *
 * @author Angie
 */
public class userForm extends javax.swing.JFrame {

    /**
     * Creates new form userForm
     */
    public userForm() {
        initComponents();
    }
       public void close(){
        this.dispose();
        dashboard dash = new dashboard();
        dash.setVisible(true);
        manageUser up = new manageUser();
        dash.maindesktop.add(up).setVisible(true);
    }
      int validateRegister(){
         int result;
        if(fname.getText().isEmpty() || email.getText().isEmpty() || pword.getText().isEmpty() || uname.getText().isEmpty() || con.getText().isEmpty()){
            result = 0;
        }else{
            result = 1;
        }
        return result;
    }
      public String action;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        username1 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        username2 = new javax.swing.JLabel();
        username3 = new javax.swing.JLabel();
        username4 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        con = new javax.swing.JTextField();
        pword = new javax.swing.JTextField();
        username6 = new javax.swing.JLabel();
        username7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        st_label = new javax.swing.JLabel();
        u_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username1.setBackground(new java.awt.Color(204, 204, 204));
        username1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username1.setForeground(new java.awt.Color(255, 255, 255));
        username1.setText("Id:");
        jPanel1.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        fname.setBackground(new java.awt.Color(204, 204, 204));
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 230, 30));

        email.setBackground(new java.awt.Color(204, 204, 204));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 230, 30));

        username2.setBackground(new java.awt.Color(204, 204, 204));
        username2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username2.setForeground(new java.awt.Color(255, 255, 255));
        username2.setText("Full Name:");
        jPanel1.add(username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        username3.setBackground(new java.awt.Color(204, 204, 204));
        username3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username3.setForeground(new java.awt.Color(255, 255, 255));
        username3.setText("Email:");
        jPanel1.add(username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        username4.setBackground(new java.awt.Color(204, 204, 204));
        username4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username4.setForeground(new java.awt.Color(255, 255, 255));
        username4.setText("Password:");
        jPanel1.add(username4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        uname.setBackground(new java.awt.Color(204, 204, 204));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 230, 30));

        con.setBackground(new java.awt.Color(204, 204, 204));
        con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conActionPerformed(evt);
            }
        });
        jPanel1.add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 230, 30));

        pword.setBackground(new java.awt.Color(204, 204, 204));
        pword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwordActionPerformed(evt);
            }
        });
        jPanel1.add(pword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 230, 30));

        username6.setBackground(new java.awt.Color(204, 204, 204));
        username6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username6.setForeground(new java.awt.Color(255, 255, 255));
        username6.setText("Username:");
        jPanel1.add(username6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        username7.setBackground(new java.awt.Color(204, 204, 204));
        username7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username7.setForeground(new java.awt.Color(255, 255, 255));
        username7.setText("Phone Number:");
        jPanel1.add(username7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("MEMBERS FORM");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 60));

        add.setBackground(new java.awt.Color(204, 204, 204));
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_label.setBackground(new java.awt.Color(255, 255, 255));
        st_label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        st_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        st_label.setText("Label");
        add.add(st_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, -1));

        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 140, 40));

        u_id.setBackground(new java.awt.Color(204, 204, 204));
        u_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_idActionPerformed(evt);
            }
        });
        jPanel1.add(u_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conActionPerformed

    private void u_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_idActionPerformed

    private void pwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwordActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        if(action.equals("Add")){

            int check = validateRegister();
            if(check == 1){
                configclass dbc = new configclass();
                int result = dbc.insertData("INSERT INTO users (u_fname, u_email, u_password, u_username, u_phone, u_status) "
                    + "VALUES ('"+fname.getText()+"', '"+email.getText()+"', '"+pword+"', '"+uname.getText()+"', '"+con.getText()+"', 'Pending')");
                if(result == 1){
                    JOptionPane.showMessageDialog(null, "Successfully Save!");
                    close();
                }else{
                    System.out.println("Saving Data Failed!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "All fields are required!");
            }

        }else if(action.equals("Update")){
            configclass dbc = new configclass();
            dbc.updateData("UPDATE users SET u_fname = '"+fname.getText()+"', u_email = '"+email.getText()+"',"
                + " u_password = '"+pword.getText()+"', u_username = '"+uname.getText()+"', "
                + "u_phone = '"+con.getText()+"' WHERE u_id  = '"+u_id.getText()+"'");
            close();
        }else{
            JOptionPane.showMessageDialog(null, "No action selected!");
            close();
        }
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
   
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
      
    }//GEN-LAST:event_addMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel add;
    public javax.swing.JTextField con;
    public javax.swing.JTextField email;
    public javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JTextField pword;
    public javax.swing.JLabel st_label;
    public javax.swing.JTextField u_id;
    public javax.swing.JTextField uname;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username3;
    private javax.swing.JLabel username4;
    private javax.swing.JLabel username6;
    private javax.swing.JLabel username7;
    // End of variables declaration//GEN-END:variables
}
