
import config.configclass;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        username1 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        username2 = new javax.swing.JLabel();
        username3 = new javax.swing.JLabel();
        username4 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        uname5 = new javax.swing.JTextField();
        cpword = new javax.swing.JTextField();
        pword = new javax.swing.JTextField();
        username6 = new javax.swing.JLabel();
        username7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username1.setBackground(new java.awt.Color(204, 204, 204));
        username1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username1.setForeground(new java.awt.Color(255, 255, 255));
        username1.setText("Confirm Password:");
        jPanel1.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        fname.setBackground(new java.awt.Color(204, 204, 204));
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 230, 30));

        email.setBackground(new java.awt.Color(204, 204, 204));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 230, 30));

        username2.setBackground(new java.awt.Color(204, 204, 204));
        username2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username2.setForeground(new java.awt.Color(255, 255, 255));
        username2.setText("Full Name:");
        jPanel1.add(username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        username3.setBackground(new java.awt.Color(204, 204, 204));
        username3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username3.setForeground(new java.awt.Color(255, 255, 255));
        username3.setText("Email:");
        jPanel1.add(username3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        username4.setBackground(new java.awt.Color(204, 204, 204));
        username4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username4.setForeground(new java.awt.Color(255, 255, 255));
        username4.setText("Password:");
        jPanel1.add(username4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        uname.setBackground(new java.awt.Color(204, 204, 204));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 230, 30));

        uname5.setBackground(new java.awt.Color(204, 204, 204));
        uname5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uname5ActionPerformed(evt);
            }
        });
        jPanel1.add(uname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 230, 30));

        cpword.setBackground(new java.awt.Color(204, 204, 204));
        cpword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpwordActionPerformed(evt);
            }
        });
        jPanel1.add(cpword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 230, 30));

        pword.setBackground(new java.awt.Color(204, 204, 204));
        pword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwordActionPerformed(evt);
            }
        });
        jPanel1.add(pword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 230, 30));

        username6.setBackground(new java.awt.Color(204, 204, 204));
        username6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username6.setForeground(new java.awt.Color(255, 255, 255));
        username6.setText("Username:");
        jPanel1.add(username6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        username7.setBackground(new java.awt.Color(204, 204, 204));
        username7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username7.setForeground(new java.awt.Color(255, 255, 255));
        username7.setText("Phone Number:");
        jPanel1.add(username7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("REGISTRATION");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 60));

        register.setBackground(new java.awt.Color(255, 255, 255));
        register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        register.setForeground(new java.awt.Color(51, 51, 51));
        register.setText("Register");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerMouseExited(evt);
            }
        });
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 220, 30));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 540, 430));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void uname5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uname5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uname5ActionPerformed

    private void cpwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpwordActionPerformed

    private void pwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwordActionPerformed

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseEntered

    }//GEN-LAST:event_registerMouseEntered

    private void registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseExited

    }//GEN-LAST:event_registerMouseExited

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
    String fullName = fname.getText();
    String userEmail = email.getText();
    String phoneNumber = uname5.getText(); // Make sure your variable name is 'phone'
    String userName = uname.getText();
    String password = pword.getText();
    String confirmPass = cpword.getText(); // Assuming variable name 'cpword'

    // 1. Basic Validation
    if(fullName.isEmpty() || userEmail.isEmpty() || userName.isEmpty() || password.isEmpty()){
        JOptionPane.showMessageDialog(null, "All fields are required!");
    } 
    // 2. Check if passwords match
    else if(!password.equals(confirmPass)){
        JOptionPane.showMessageDialog(null, "Passwords do not match!");
    }
    // 3. If everything is okay, save to database
    else {
        configclass conf = new configclass();
        
        String sql = "INSERT INTO users (u_fname, u_email, u_phone, u_username, u_password, u_status) "
                   + "VALUES (?, ?, ?, ?, ?, 'Active')";

        if(conf.insertData(sql, fullName, userEmail, phoneNumber, userName, password) == 1) {
        JOptionPane.showMessageDialog(null, "Registration Successful!");

        // 1. Create the Login window object
        logIn loginFrame = new logIn(); 

        // 2. Make it visible to the user
        loginFrame.setVisible(true); 

        // 3. Close the current Registration window
        this.dispose(); 
    }
    }
    }//GEN-LAST:event_registerActionPerformed

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpword;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField pword;
    private javax.swing.JButton register;
    private javax.swing.JTextField uname;
    private javax.swing.JTextField uname5;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username3;
    private javax.swing.JLabel username4;
    private javax.swing.JLabel username6;
    private javax.swing.JLabel username7;
    // End of variables declaration//GEN-END:variables
}
